# Generated by Django 4.0.4 on 2022-05-17 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aticle',
            new_name='Article',
        ),
    ]
